title: Crumble motor buggy
hero_image: images/banner.png
description: Create a motor buggy using Crumble
version: 4
listed: false
copyedit: false
last_tested: "2019-06-26"
steps:
  - title: Introduction
  - title: Design your motor buggy
  - title: Make your buggy
  - title: Wire up your buggy
  - title: Write a test program for the motors
  - title: Control the speed and turns
  - title: "Challenge: Send your buggy 'there and back again'"
    challenge: true
  - title: Create a random journey
  - title: Create random journey that is even more random!
  - title: "Challenge: create a maze"
    challenge: true
  - title: "Challenge: play 'Crumball'"
    challenge: true
