title: build-crumble-motor-buggy
hero_image: images/banner.png
description: build-crumble-motor-buggy description
version: 4
listed: false
copyedit: false
last_tested: "2019-06-26"
steps:
  - title: Introduction
  - title: What does a motor buggy look like?
  - title: Making your buggy
  - title: Wiring up your Crumble buggy
  - title: Test code for motors
  - title: orwards, backwards, right and left